### ISSUE TITLE
运行 BusyBoxTest 报错

### ISSUE THREAD

**Issue by xiamulo** [zhkl0228/emulator#3]
Exception in thread "main" java.lang.UnsatisfiedLinkError: no unicorn_java in java.library.path

**Comment by zhkl0228** [comment]
linux系统：-Djava.library.path=prebuilt/linux64
windows系统要自行编译逆向三剑客，unicorn，keystone，capstone，以及unicorn_java

**Comment by zhkl0228** [comment]
最新提交包含有win32跟win64的预编译，自行测试
