### ISSUE TITLE
请问下如果native方法参数有Context如何处理

### ISSUE THREAD

**Issue by qtfreet00** [zhkl0228/emulator#5]
我看了下示例中几个都是常规的基本参数，没有跟android环境相关的参数类型

**Comment by zhkl0228** [comment]
src/test 目录下有个com.xunmeng.pinduoduo.secure.DeviceNative 里面有个例子

**Comment by freemanZYQ** [comment]
https://bbs.pediy.com/thread-249732.htm 这里作者有回复
Object custom = null;
DvmObject context = vm.resolveClass("android/content/Context").newObject(custom);

**Comment by pkw123456** [comment]
作者你好，你说的com.xunmeng.pinduoduo.secure.DeviceNative这个类我在项目里找不到，能说一下具体位置吗？

**Comment by pkw123456** [comment]
@zhkl0228

**Comment by RickyCong** [comment]
https://github.com/zhkl0228/unidbg/blob/4e7c3c1f478ed9c97c30fff16995105bf949f40d/src/test/java/com/xunmeng/pinduoduo/secure/DeviceNative.java
