### ISSUE TITLE
so里依赖其他自定义的java类的情况

### ISSUE THREAD

**Issue by qtfreet00** [zhkl0228/emulator#7]
如native入口为A.java ,里面为public native a();  在native里findclass（B），并且反射调用了B.java中的方法，这种多个java类依赖的情况如何处理

**Comment by zhkl0228** [comment]
DeviceNative 有调用 android 库方法的实例，里面有调用获取 imei 以及 imsi 等系统库方法，跟调用 B.java 原理一样
