### ISSUE TITLE
抖音libcms.so RegisterNatives输出乱码

### ISSUE THREAD

**Issue by jtduan** [zhkl0228/emulator#9]
在运行抖音libcms.so JNI_OnLoad时会出现乱码的情况，这是对方做了一些防范措施吗？不知作者是否有解决方案？
![image](https://user-images.githubusercontent.com/14127164/57564563-899ac180-73e0-11e9-866d-eccf29dffa78.png)

**Comment by zhkl0228** [comment]
so发上来看下

**Comment by jtduan** [comment]
[libcms.so.zip](https://github.com/zhkl0228/emulator/files/3168809/libcms.so.zip)
这是抖音1.8.3版本的libcms.so

**Comment by zhkl0228** [comment]
你写的测试代码可否发上来测试下

**Comment by zhkl0228** [comment]
程序存在bug已修复，下载最新代码即可
